--CRIAÇÃO DE UM USUARIO PARA ACESSAR O BANCO
CREATE LOGIN alunoUC13
WITH PASSWORD = '12345';

--ATRIBUINDO O PERFIL DO LOGIN ALUNO PARA O USUARIO
CREATE USER alunoUC13 FOR LOGIN alunoUC13;

--ATRIBUINDO PERMISSAO APENAS PARA SELECT A ESSE USUARIO
GRANT SELECT TO alunoUC13;